"""Migrationn

Revision ID: c13e8ab6aad9
Revises: efd188ab8acb
Create Date: 2024-12-11 17:35:11.751811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision: str = 'c13e8ab6aad9'
down_revision: Union[str, None] = 'efd188ab8acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=True)
    op.create_index(op.f('ix_teachers_name'), 'teachers', ['name'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('student_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('teacher_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_title'), 'schedules', ['title'], unique=False)
    op.drop_index('id', table_name='dersprogrami')
    op.drop_index('ix_dersprogrami_ders', table_name='dersprogrami')
    op.drop_index('ix_dersprogrami_ogretmen_id', table_name='dersprogrami')
    op.drop_index('ix_dersprogrami_saat', table_name='dersprogrami')
    op.drop_index('ix_dersprogrami_sinif', table_name='dersprogrami')
    op.drop_table('dersprogrami')
    op.drop_index('id', table_name='ogretmenler')
    op.drop_index('ix_ogretmenler_ad', table_name='ogretmenler')
    op.drop_index('ix_ogretmenler_brans', table_name='ogretmenler')
    op.drop_index('ix_ogretmenler_iletisim', table_name='ogretmenler')
    op.drop_index('ix_ogretmenler_soyad', table_name='ogretmenler')
    op.drop_table('ogretmenler')
    op.drop_index('id', table_name='ogrenciler')
    op.drop_index('ix_ogrenciler_ad', table_name='ogrenciler')
    op.drop_index('ix_ogrenciler_iletisim', table_name='ogrenciler')
    op.drop_index('ix_ogrenciler_ogrenci_numarasi', table_name='ogrenciler')
    op.drop_index('ix_ogrenciler_sinif', table_name='ogrenciler')
    op.drop_index('ix_ogrenciler_soyad', table_name='ogrenciler')
    op.drop_table('ogrenciler')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ogrenciler',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('ad', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('soyad', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('ogrenci_numarasi', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('sinif', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('iletisim', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('kayit_tarihi', mysql.DATETIME(), nullable=False),
    sa.Column('guncelleme_tarihi', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_ogrenciler_soyad', 'ogrenciler', ['soyad'], unique=False)
    op.create_index('ix_ogrenciler_sinif', 'ogrenciler', ['sinif'], unique=False)
    op.create_index('ix_ogrenciler_ogrenci_numarasi', 'ogrenciler', ['ogrenci_numarasi'], unique=True)
    op.create_index('ix_ogrenciler_iletisim', 'ogrenciler', ['iletisim'], unique=False)
    op.create_index('ix_ogrenciler_ad', 'ogrenciler', ['ad'], unique=False)
    op.create_index('id', 'ogrenciler', ['id'], unique=True)
    op.create_table('ogretmenler',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('ad', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('soyad', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('brans', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('iletisim', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('kayit_tarihi', mysql.DATETIME(), nullable=False),
    sa.Column('guncelleme_tarihi', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_ogretmenler_soyad', 'ogretmenler', ['soyad'], unique=False)
    op.create_index('ix_ogretmenler_iletisim', 'ogretmenler', ['iletisim'], unique=False)
    op.create_index('ix_ogretmenler_brans', 'ogretmenler', ['brans'], unique=False)
    op.create_index('ix_ogretmenler_ad', 'ogretmenler', ['ad'], unique=False)
    op.create_index('id', 'ogretmenler', ['id'], unique=True)
    op.create_table('dersprogrami',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('sinif', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('ders', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('saat', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('ogretmen_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('kayit_tarihi', mysql.DATETIME(), nullable=False),
    sa.Column('guncelleme_tarihi', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['ogretmen_id'], ['ogretmenler.id'], name='dersprogrami_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_dersprogrami_sinif', 'dersprogrami', ['sinif'], unique=False)
    op.create_index('ix_dersprogrami_saat', 'dersprogrami', ['saat'], unique=False)
    op.create_index('ix_dersprogrami_ogretmen_id', 'dersprogrami', ['ogretmen_id'], unique=False)
    op.create_index('ix_dersprogrami_ders', 'dersprogrami', ['ders'], unique=False)
    op.create_index('id', 'dersprogrami', ['id'], unique=True)
    op.drop_index(op.f('ix_schedules_title'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_teachers_name'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
